language: php
php:
  #- 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  #- hhvm
# Commands to be run before your environment runs.
install:
   - composer self-update
   - composer update --prefer-dist
#before_script:
#  - composer self-update
#  - composer install --prefer-source --no-interaction --dev
#before_install:
#  - php composer.phar self-update
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
env:
  global:
    - SKIP_CLEANUP=1
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.0.1
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.8.0.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - bot@codisto.com
    on_success: always
    on_failure: always

branches:
  only:
    - master
    - development
    - bm_travis_ci
