language: php
php:
  #- 5.2
  #- 5.3
  #- 5.4
  - 5.5
  #- 5.6
  #- hhvm
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
env:
  global:
    #- MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.0.1
  #- MAGENTO_VERSION=magento-ce-1.8.1.0
  #- MAGENTO_VERSION=magento-ce-1.8.0.0
  #- MAGENTO_VERSION=magento-ce-1.7.0.2
script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
#cache:
  #TODO think about caching the magento builds so it doesn't have to download them each time
notifications:
  email:
    recipients:
      - bot@codisto.com
    on_success: always
    on_failure: always

branches:
  only:
    - bm_travis_ci
    - master
    - development

#use container based infrastructure for faster building is the default now , confirm if I need sudo and uncomment below if required
#there are ways to install software using travis without sudo so be certain 
#sudo: required

